# Generated by Django 3.1 on 2020-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_recipe', models.BooleanField(default=False)),
                ('champions', models.ManyToManyField(to='champions.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='BigItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('champions', models.ManyToManyField(to='champions.Champion')),
            ],
        ),
    ]
